prueba2023/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PlatosController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProformasController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\TransferProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login2');
});

Route::get('/prueba', function () {
    return view('prueba');
});

Route::get('sales/reports_day', [ReportController::class, 'reports_day'])->name('reports.day');
Route::get('sales/reports_date', [ReportController::class, 'reports_date'])->name('reports.date');
Route::post('sales/reports_result', [ReportController::class, 'reports_result'])->name('reports.result');

Route::resource('users', UserController::class)->names('users');

Route::resource('categories', CategoryController::class)->names('categories');

Route::resource('platos', PlatosController::class)->names('platos');

Route::resource('warehouses', WarehouseController::class)->names('warehouses');

Route::resource('transfers', TransferProductController::class)->names('transfers');

Route::resource('marcas', \App\Http\Controllers\MarcaController::class);

Route::resource('medidas', \App\Http\Controllers\MedidaController::class);

Route::resource('clients', ClientController::class)->names('clients');

Route::resource('providers', ProviderController::class)->names('providers');

Route::resource('products', ProductController::class)->names('products');
Route::get('products/pdf/{product}', [ProductController::class, 'pdf'])->name('products.pdf');
Route::get('change_status/products/{product}', [ProductController::class, 'change_status'])->name('products.change.status');

Route::resource('purchases', PurchaseController::class)->names('purchases');
Route::post('change_status/purchases/{purchase}', [PurchaseController::class, 'change_status'])->name('purchases.change.status');
Route::get('purchases/pdf/{purchase}', [PurchaseController::class, 'pdf'])->name('purchases.pdf');

Route::resource('proformas', ProformasController::class)->names('proformas');
Route::get('proformas/pdf/{proforma}', [ProformasController::class, 'pdf'])->name('proformas.pdf');

Route::resource('sales', SaleController::class)->names('sales');
Route::get('sales/pdf/{sale}', [SaleController::class, 'pdf'])->name('sales.pdf');
Route::post('change_status/sales/{sale}', [SaleController::class, 'change_status'])->name('sales.change.status');

Route::resource('roles', RoleController::class)->names('roles');
Route::resource('permissions', PermissionController::class)->names('permissions');

Route::get('get_products_by_barcode', [ProductController::class, 'get_products_by_barcode'])->name('get_products_by_barcode');
Route::get('get_products_by_id', [App\Http\Controllers\ProductController::class, 'get_products_by_id'])->name('get_products_by_id');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

prueba2023/resources/views/admin/warehouses/_form.blade.php
  <div class="form-group col-12">
    <label for="name">Nombre : </label>
    <input type="text" name="name" id="name" class="form-control" placeholder="" required>
  </div>
  <div class="form-group col-12">
    <label for="location">Ubicacion : </label>
    <input type="text" name="location" id="location" class="form-control" placeholder="" required>
  </div>

prueba2023/resources/views/admin/warehouses/create.blade.php
@extends('layouts.admin')

@section('title', 'Registrar Almacen')
    
@section('options')
    {{-- <li class="nav-item nav-settings d-none d-lg-block">
        <a href="#" class="nav-link">
            <i class="fa fa-elipsis-h"></i>
        </a>
    </li> --}}
@endsection

@section('content')
    <div class="content-wrapper">
        <div >
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('warehouses.index') }}">Almacenes</a></li>
                    <li class="breadcrumb-item active">Registrar Almacen</li>
                </ol>
            </nav>
        </div>
        <div class="container ">
            <div class="abs-center">
                <div class="card card-primary">
                    <div class="card-header" style="background-color:rgb(57, 62, 66); color:white">
                        <h1 style="text-align:center">REGISTRAR NUEVO ALMACEN</h1>
                    </div>
                    <div class="card-body">

                        {!! Form::open(['route' => 'warehouses.store', 'method' => 'POST']) !!}

                            @include('admin.warehouses._form')

                            <div class="card-footer text-center">
                                <button type="submit" class="btn btn-success mr-2">+ Registrar</button>
                                <a href="{{ route('warehouses.index') }}" class="btn btn-info">Cancelar</a>
                            </div>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    
@endsection

prueba2023/resources/views/admin/warehouses/edit.blade.php
@extends('layouts.admin')

@section('title', 'Editar Almacen')
    
@section('options')
    {{-- <li class="nav-item nav-settings d-none d-lg-block">
        <a href="#" class="nav-link">
            <i class="fa fa-elipsis-h"></i>
        </a>
    </li> --}}
@endsection

@section('content')
    <div class="content-wrapper">
        <div >
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('warehouses.index') }}">Almacenes</a></li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </nav>
        </div>

        <div class="container ">
            <div class="abs-center">
                <div class="card card-primary">
                    <div class="card-header" style="background-color:rgb(57, 62, 66); color:white">
                        <h1 style="text-align:center">EDITAR ALMACEN</h1>
                    </div>
                    <div class="card-body">

                        {!! Form::model($warehouse, ['route' => ['warehouses.update', $warehouse], 'method' => 'PUT']) !!}

                          <div class="form-group">
                            <label for="name">Nombre : </label>
                            <input type="text" name="name" id="name" class="form-control" value="{{ $warehouse->name }}" placeholder="" required>
                          </div>
                          <div class="form-group">
                            <label for="location">Ubicacion : </label>
                            <input type="text" name="location" id="location" class="form-control" value="{{ $warehouse->location }}" placeholder="" required>
                          </div>

                            <div class="text-center card-footer">
                                <button type="submit" class="btn btn-success mr-2">Actualizar</button>
                                <a href="{{ route('warehouses.index') }}" class="btn btn-info">Cancelar</a>
                            </div>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    
@endsection

prueba2023/resources/views/admin/warehouses/index.blade.php
@extends('layouts.admin')

@section('title', 'Gestión de Almacenes')
    
@section('create')

@endsection

@section('styles')
    <style type="text/css">
        .unstyled-button {
            border: none;
            padding: 0;
            background: none
        }
    </style>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.3.0/css/responsive.dataTables.min.css">
@endsection

@section('content')
    <div class="content-wrapper">
        <div>
            <h3 class="text-center">
                Gestión de Almacenes
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item active">Almacenes</li>
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <div class="d-flex justify-content-between mb-4">
                            <h4 class="">Lista de Almacenes</h4>
                            <div>                  
                                <div>
                                    <a href="{{ route('warehouses.create') }}"  class="btn btn-success">+ Agregar Almacen</a>
                                </div>
                            </div>
                        </div>

                        <div>
                            <table id="detalle" class="table">
                                <thead class="bg-dark text-white">
                                    <tr>
                                        <th>Id</th>
                                        <th>Nombre</th>
                                        <th>Ubicacion</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($warehouses as $warehouse)
                                        <tr>
                                            <th scope="row">{{ $warehouse->id }}</th>
                                            <td>{{ $warehouse->name }}</td>
                                            <td>{{ $warehouse->location }}</td>
                                            <td>
                                                {!! Form::open(['route' => ['warehouses.destroy',$warehouse], 'method' => 'DELETE']) !!}

                                                    <a href="{{ route('warehouses.edit', $warehouse) }}" title="Editar" class="btn btn-warning" style="padding: 6px 6px 6px 6px">
                                                        <i class="far fa-edit" style="color: black"></i>
                                                    </a>

                                                    <button type="submit" title="Eliminar" class="btn btn-danger" style="padding: 6px 6px 6px 6px">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>

                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {

            $('#detalle').DataTable({

                "order": [
                    [0, 'desc']
                ],
                "lengthMenu": [
                    [5, 10, 50, -1],
                    [5, 10, 50, "Todo"]
                ],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Ningun registro encontrado",
                    "info": "Mostrando la página _PAGE_ de _PAGES_",
                    "infoEmpty": "",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    'search': 'Buscar:',
                    'paginate': {
                        'next': 'Siguiente',
                        'previous': 'Anterior'
                    }

                },
            });

        });
    </script>
@endsection