prueba2023/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PlatosController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProformasController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\TransferProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login2');
});

Route::get('/prueba', function () {
    return view('prueba');
});

Route::get('sales/reports_day', [ReportController::class, 'reports_day'])->name('reports.day');
Route::get('sales/reports_date', [ReportController::class, 'reports_date'])->name('reports.date');
Route::post('sales/reports_result', [ReportController::class, 'reports_result'])->name('reports.result');

Route::resource('users', UserController::class)->names('users');

Route::resource('categories', CategoryController::class)->names('categories');

Route::resource('platos', PlatosController::class)->names('platos');

Route::resource('warehouses', WarehouseController::class)->names('warehouses');

Route::resource('transfers', TransferProductController::class)->names('transfers');

Route::resource('marcas', \App\Http\Controllers\MarcaController::class);

Route::resource('medidas', \App\Http\Controllers\MedidaController::class);

Route::resource('clients', ClientController::class)->names('clients');

Route::resource('providers', ProviderController::class)->names('providers');

Route::resource('products', ProductController::class)->names('products');
Route::get('products/pdf/{product}', [ProductController::class, 'pdf'])->name('products.pdf');
Route::get('change_status/products/{product}', [ProductController::class, 'change_status'])->name('products.change.status');

Route::resource('purchases', PurchaseController::class)->names('purchases');
Route::post('change_status/purchases/{purchase}', [PurchaseController::class, 'change_status'])->name('purchases.change.status');
Route::get('purchases/pdf/{purchase}', [PurchaseController::class, 'pdf'])->name('purchases.pdf');

Route::resource('proformas', ProformasController::class)->names('proformas');
Route::get('proformas/pdf/{proforma}', [ProformasController::class, 'pdf'])->name('proformas.pdf');

Route::resource('sales', SaleController::class)->names('sales');
Route::get('sales/pdf/{sale}', [SaleController::class, 'pdf'])->name('sales.pdf');
Route::post('change_status/sales/{sale}', [SaleController::class, 'change_status'])->name('sales.change.status');

Route::resource('roles', RoleController::class)->names('roles');
Route::resource('permissions', PermissionController::class)->names('permissions');

Route::get('get_products_by_barcode', [ProductController::class, 'get_products_by_barcode'])->name('get_products_by_barcode');
Route::get('get_products_by_id', [App\Http\Controllers\ProductController::class, 'get_products_by_id'])->name('get_products_by_id');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

prueba2023/app/Models/Marca.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Marca extends Model
{
    use HasFactory;
    protected $fillable = ['nombre'];
}

prueba2023/app/Http/Controllers/MarcaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\StoreRequest;
use App\Models\Marca;
use Illuminate\Http\Request;

class MarcaController extends Controller
{
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // abort_if(Gate::denies('category_index'), 403);
        $marcas = Marca::all();

        return view('admin.marca.index', compact('marcas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // abort_if(Gate::denies('category_create'), 403);

        return view('admin.marca.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $marca = new Marca();
        $marca->nombre = $request->nombre;
        $marca->save();
        return redirect()->route('marcas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Marca $marca)
    {
        // abort_if(Gate::denies('category_show'), 403);

        return view('admin.marca.show', compact('marca'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Marca  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Marca $marca)
    {
        // abort_if(Gate::denies('category_edit'), 403);

        return view('admin.marca.edit', compact('marca'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Marca  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Marca $marca)
    {
        $marca->update($request->all());
        
        return redirect()->route('marcas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Marca $marca)
    {
        // abort_if(Gate::denies('category_destroy'), 403);
        $marca->delete();
        return redirect()->route('marcas.index');
    }
}

prueba2023/resources/views/admin/marca/_form.blade.php
<div class="form-group col-12">
  <label for="nombre">Nombre :</label>
  <input type="text" name="nombre" id="nombre" class="form-control" placeholder="" required>
</div>

prueba2023/resources/views/admin/marca/create.blade.php
@extends('layouts.admin')

@section('title', 'Registrar Marca')
    
@section('options')

@endsection

@section('content')
    <div class="content-wrapper">
        <div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('marcas.index') }}">Marca</a></li>
                    <li class="breadcrumb-item active">Registrar Marca</li>
                </ol>
            </nav>
        </div>

        <div class="container ">
            <div class="abs-center">
                <div class="card card-primary">
                    <div class="card-header" style="background-color:rgb(57, 62, 66); color:white">
                        <h1 style="text-align:center">REGISTRAR NUEVA MARCA</h1>
                    </div>
                    <div class="card-body">

                        {!! Form::open(['route' => 'marcas.store', 'method' => 'POST']) !!}

                            @include('admin.marca._form')
                            <div class="card-footer text-center">
                                <button type="submit" class="btn btn-success mr-2">+ Registrar</button>
                                <a href="{{ route('marcas.index') }}" class="btn btn-info">Cancelar</a>
                            </div>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    
@endsection

prueba2023/resources/views/admin/marca/edit.blade.php
@extends('layouts.admin')

@section('title', 'Editar Marca')
    
@section('options')
    {{-- <li class="nav-item nav-settings d-none d-lg-block">
        <a href="#" class="nav-link">
            <i class="fa fa-elipsis-h"></i>
        </a>
    </li> --}}
@endsection

@section('content')
    <div class="content-wrapper">
        <div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('marcas.index') }}">Categoria</a></li>
                    <li class="breadcrumb-item active">Editar Categoría</li>
                </ol>
            </nav>
        </div>

        <div class="container ">
            <div class="abs-center">
                <div class="card card-primary">
                    <div class="card-header" style="background-color:rgb(57, 62, 66); color:white">
                        <h1 style="text-align:center">EDITAR MARCA</h1>
                    </div>
                    <div class="card-body">

                        {!! Form::model($marca, ['route' => ['marcas.update', $marca], 'method' => 'PUT']) !!}

                          <div class="form-group">
                            <label for="nombre">Nombre :</label>
                            <input type="text" name="nombre" id="nombre" class="form-control" value="{{ $marca->nombre }}" placeholder="" required>
                          </div>
                          <div class="text-center card-footer">
                            <button type="submit" class="btn btn-success mr-2">Actualizar</button>
                            <a href="{{ route('marcas.index') }}" class="btn btn-info">Cancelar</a>
                          </div>
                    

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    
@endsection

prueba2023/resources/views/admin/marca/index.blade.php
@extends('layouts.admin')

@section('title', 'Gestión de Marcas')
    
@section('create')
{{-- <li class="nav-item d-none d-lg-flex">
    <a class="nav-link" href="{{ route('categories.create') }}">
        <span class="btn btn-primary">+ Crear Categoria</span>
    </a>
</li> --}}
@endsection

@section('styles')
    <style type="text/css">
        .unstyled-button {
            border: none;
            padding: 0;
            background: none
        }
    </style>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.3.0/css/responsive.dataTables.min.css">
@endsection

@section('content')
    <div class="content-wrapper">
        <div>
            <h3 class="text-center">
                Gestión de Marcas
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item active">Marca</li>
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <div class="d-flex justify-content-between mb-4">
                            <h4 class="card-title"> Marcas</h4>
                            <div>
                                <div>
                                    <a href="{{ route('marcas.create') }}" class="btn btn-success">+ Agregar Marca</a>
                                </div>
                            </div>
                        </div>

                        <div>
                            <table id="detalle" class="table">
                                <thead class="bg-dark text-white">
                                    <tr>
                                        <th>Id</th>
                                        <th>Nombre</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($marcas as $marca)
                                        <tr>
                                            <th scope="row">{{ $marca->id }}</th>
                                            <td>{{ $marca->nombre }}</td>
                                            <td>
                                                {!! Form::open(['route' => ['marcas.destroy',$marca], 'method' => 'DELETE']) !!}

                                                    <a href="{{ route('marcas.edit', $marca) }}" title="Editar" class="btn btn-warning" style="padding: 6px 6px 6px 6px">
                                                        <i class="far fa-edit" style="color: black"></i>
                                                    </a>

                                                    <button type="submit" title="Eliminar" class="btn btn-danger" style="padding: 6px 6px 6px 6px">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>

                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {

            $('#detalle').DataTable({

                "order": [
                    [0, 'desc']
                ],
                "lengthMenu": [
                    [5, 10, 50, -1],
                    [5, 10, 50, "Todo"]
                ],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Ningun registro encontrado",
                    "info": "Mostrando la página _PAGE_ de _PAGES_",
                    "infoEmpty": "",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    'search': 'Buscar:',
                    'paginate': {
                        'next': 'Siguiente',
                        'previous': 'Anterior'
                    }

                },
            });

        });
    </script>
@endsection