prueba2023/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PlatosController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProformasController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\TransferProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login2');
});

Route::get('/prueba', function () {
    return view('prueba');
});

Route::get('sales/reports_day', [ReportController::class, 'reports_day'])->name('reports.day');
Route::get('sales/reports_date', [ReportController::class, 'reports_date'])->name('reports.date');
Route::post('sales/reports_result', [ReportController::class, 'reports_result'])->name('reports.result');

Route::resource('users', UserController::class)->names('users');

Route::resource('categories', CategoryController::class)->names('categories');

Route::resource('platos', PlatosController::class)->names('platos');

Route::resource('warehouses', WarehouseController::class)->names('warehouses');

Route::resource('transfers', TransferProductController::class)->names('transfers');

Route::resource('marcas', \App\Http\Controllers\MarcaController::class);

Route::resource('medidas', \App\Http\Controllers\MedidaController::class);

Route::resource('clients', ClientController::class)->names('clients');

Route::resource('providers', ProviderController::class)->names('providers');

Route::resource('products', ProductController::class)->names('products');
Route::get('products/pdf/{product}', [ProductController::class, 'pdf'])->name('products.pdf');
Route::get('change_status/products/{product}', [ProductController::class, 'change_status'])->name('products.change.status');

Route::resource('purchases', PurchaseController::class)->names('purchases');
Route::post('change_status/purchases/{purchase}', [PurchaseController::class, 'change_status'])->name('purchases.change.status');
Route::get('purchases/pdf/{purchase}', [PurchaseController::class, 'pdf'])->name('purchases.pdf');

Route::resource('proformas', ProformasController::class)->names('proformas');
Route::get('proformas/pdf/{proforma}', [ProformasController::class, 'pdf'])->name('proformas.pdf');

Route::resource('sales', SaleController::class)->names('sales');
Route::get('sales/pdf/{sale}', [SaleController::class, 'pdf'])->name('sales.pdf');
Route::post('change_status/sales/{sale}', [SaleController::class, 'change_status'])->name('sales.change.status');

Route::resource('roles', RoleController::class)->names('roles');
Route::resource('permissions', PermissionController::class)->names('permissions');

Route::get('get_products_by_barcode', [ProductController::class, 'get_products_by_barcode'])->name('get_products_by_barcode');
Route::get('get_products_by_id', [App\Http\Controllers\ProductController::class, 'get_products_by_id'])->name('get_products_by_id');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

prueba2023/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['code', 'codigo', 'name', 'stock', 'image', 'price', 'status', 'category_id', 'provider_id', 'marca_id','medida_id'];

    public function add_stock($quantity)
    {
        /* $this->update([
            'stock' => DB::raw("stock + $quantity")
        ]); */

        $this->increment('stock', $quantity);
    }

    public function subtract_stock($quantity)
    {
        /* $this->update([
            'stock' => DB::raw("stock - $quantity")
        ]); */

        $this->decrement('stock', $quantity);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }
}

prueba2023/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\StoreRequest;
use App\Http\Requests\Product\UpdateRequest;
use App\Models\Category;
use App\Models\Marca;
use App\Models\Medida;
use App\Models\Product;
use App\Models\Provider;
use App\Models\Warehouse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use DB;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        abort_if(Gate::denies('product_index'), 403);

        $products = Product::all();

        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('product_create'), 403);

        $categories = Category::get();
        $providers = Provider::get();
        $medidas = Medida::get();
        $marcas = Marca::get();
        $warehouses = Warehouse::all();

        return view('admin.product.create', compact('categories', 'providers','marcas','medidas','warehouses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cantidad = 0;
        if($request->hasFile('picture')){
            $file = $request->file('picture');
            $image_name = time() . '_' . $file->getClientOriginalName();
            $file->move(public_path("/image"), $image_name);
        }
        $product = Product::create($request->all()+[
            'image'=>$image_name,
        ]);

        if($product){
            $ids = $request->warehouses_id;
            foreach($ids as $id){
                DB::table('product_warehouses')->insert([
                    'product_id'=>$product->id,
                    'warehouse_id'=>$id,
                    'quantity'=>$_POST['warehouse_'.$id]
                ]);
                $cantidad+=$_POST['warehouse_'.$id];
            }

            $uproduct = Product::findOrFail($product->id);
            $uproduct->stock = $cantidad;
            $uproduct->update();
            $cantidad = 0;
        }
        
        if ($request->code == "") {
            $numero = $product->id;
            $numeroConCeros = str_pad($numero, 8, "0", STR_PAD_LEFT);

            $product->update([
                'code' => $numeroConCeros
            ]);
        }
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        abort_if(Gate::denies('product_show'), 403);

        return view('admin.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        abort_if(Gate::denies('product_edit'), 403);

        $categories = Category::all();
        $providers = Provider::all();
        $medidas = Medida::all();
        $marcas = Marca::all();
        $warehouses = Warehouse::all();
        $warehouses_selected = DB::table("product_warehouses")->select('warehouse_id','quantity')->where('product_id',$product->id)->get();

        return view('admin.product.edit', compact('product', 'categories', 'providers','marcas','medidas','warehouses','warehouses_selected'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->update($request->all());
        $cantidad = 0;
        if($request->hasFile('image')){
            $file = $request->file('image');
            $image_name = time() . '_' . $file->getClientOriginalName();
            $file->move(public_path("/image"), $image_name);

            $product->update([
                'image' => $image_name
            ]);
        }

        if($product){
            DB::table('product_warehouses')->where('product_id',$product->id)->delete();
            $ids = $request->warehouses_id;
            foreach($ids as $id){
                DB::table('product_warehouses')->insert([
                    'product_id'=>$product->id,
                    'warehouse_id'=>$id,
                    'quantity'=>$_POST['warehouse_'.$id]
                ]);
                $cantidad+=$_POST['warehouse_'.$id];
            }

            $uproduct = Product::findOrFail($product->id);
            $uproduct->stock = $cantidad;
            $uproduct->update();
            $cantidad = 0;
        }

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        abort_if(Gate::denies('product_destroy'), 403);

        $product->delete();

        return redirect()->route('products.index');
    }

    public function change_status(Product $product)
    {
        if ($product->status == 'ACTIVE') {
            $product->update(['status' => 'DEACTIVATED']);
            return redirect()->back();
        } else {
            $product->update(['status' => 'ACTIVE']);
        }
        return redirect()->back();
    }


    public function get_products_by_barcode(Request $request)
    {
        if($request->ajax()){
            $products = Product::where('code',$request->code)->firstOrFail();
            return response()->json($products);
        }
    }

    public function get_products_by_id(Request $request)
    {
        if($request->ajax()){
            $products = Product::findOrFail($request->product_id);
            return response()->json($products);
        }
    }

    public function pdf(Product $product)
    {
        $compras = DB::table('purchase_details')
            ->where('purchase_details.product_id', $product->id)
            ->orderBy('purchase_details.created_at')
            ->select('quantity', 'price', 'created_at', DB::raw("'INGRESO' AS tipo"));
        $ventas = DB::table('sale_details')
            ->where('sale_details.product_id', $product->id)
            ->orderBy('sale_details.created_at')
            ->select('quantity', 'price', 'created_at', DB::raw("'SALIDA' AS tipo"));
        $existencias = $compras->union($ventas)->orderBy('created_at')->get();

        // dd($existencias);
        $subtotal = 0;
        foreach ($existencias as $key => $existencia) {
            if ($existencia->tipo == 'INGRESO') {
                $subtotal = $subtotal + $existencia->quantity;
                $existencias[$key]->saldo = $subtotal;
            } else {
                $subtotal = $subtotal - $existencia->quantity;
                $existencias[$key]->saldo = $subtotal;
            }
        }
        
        $pdf = \PDF::loadView('admin.product.pdf', compact('product', 'existencias', 'subtotal'));
        $pdf->set_paper('letter', 'landscape');
        return $pdf->stream('ReporteDeExistencia_'.$product->id.'.pdf');
    }
}

prueba2023/resources/views/admin/product/index.blade.php
@extends('layouts.admin')

@section('title', 'Gestión de Articulos')
    
@section('create')
{{-- <li class="nav-item d-none d-lg-flex">
    <a class="nav-link" href="{{ route('products.create') }}">
        <span class="btn btn-primary">+ Crear Producto</span>
    </a>
</li> --}}
@endsection

@section('styles')
    <style type="text/css">
        .unstyled-button {
            border: none;
            padding: 0;
            background: none
        }
    </style>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.3.0/css/responsive.dataTables.min.css">    
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Gestión de Artículos
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item active">Artículos</li>
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <div class="d-flex justify-content-between mb-4">
                            <h4>Lista de Artículos</h4>
                            <div>
                                    <a href="{{ route('products.create') }}" class="btn btn-success">+ Agregar Artículo</a>
                            </div>
                        </div>

                        <div>
                            <table id="detalle" class="table">
                                <thead class="bg-dark text-white">
                                    <tr>
                                        <th>Id</th>
                                        <th>Nombre</th>
                                        <th>Código</th>
                                        <th>Stock</th>
                                        <th>Estado</th>
                                        <th>Imagen</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($products as $product)
                                        <tr>
                                            <th scope="row">{{ $product->id }}</th>
                                            <td>
                                                <a href="{{ route('products.show', $product) }}">{{ $product->name }}</a>
                                            </td>
                                            <td>{{ $product->codigo }}</td>
                                            <td>{{ $product->stock }}</td>
                                            <td>
                                                @if ($product->status == 'ACTIVE' )
                                                    <a href="{{ route('products.change.status', $product) }}" class="jsgrid-button btn btn-sm btn-success" title="Activo">
                                                            Activo <i class="fas fa-check"></i>
                                                    </a>
                                                @else
                                                    <a href="{{ route('products.change.status', $product) }}" class="jsgrid-button btn btn-sm btn-danger" title="Desactivado">
                                                            Desactivado <i class="fas fa-times"></i>
                                                    </a>
                                                @endif
                                            </td>
                                            <td>
                                                <img src="{{asset('image/'.$product->image )}}"  class="img-lg rounded-circle mb-3">
                                            </td>
                                            <td>
                                                {!! Form::open(['route' => ['products.destroy',$product], 'method' => 'DELETE']) !!}

                                                <a href="{{ route('products.pdf', $product) }}" title="Editar" class="btn btn-warning" style="padding: 6px 6px 6px 6px">
                                                        <i class="fas fa-clipboard-list" style="color: black"></i>
                                                    </a>

                                                    <a href="{{ route('products.edit', $product) }}" title="Editar" class="btn btn-warning" style="padding: 6px 6px 6px 6px">
                                                        <i class="far fa-edit" style="color: black"></i>
                                                    </a>

                                                    <button type="submit" title="Eliminar" class="btn btn-danger" style="padding: 6px 6px 6px 6px">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>

                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {

            $('#detalle').DataTable({

                "order": [
                    [0, 'asc']
                ],
                "lengthMenu": [
                    [5, 10, 50, -1],
                    [5, 10, 50, "Todo"]
                ],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Ningun registro encontrado",
                    "info": "Mostrando la página _PAGE_ de _PAGES_",
                    "infoEmpty": "",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    'search': 'Buscar:',
                    'paginate': {
                        'next': 'Siguiente',
                        'previous': 'Anterior'
                    }

                },
            });

        });
    </script>
@endsection

prueba2023/resources/views/admin/product/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte Kardex</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        @page {
            margin: 0cm 0cm;
            font-family: Arial;
        }
        body {
            margin: 3cm 2cm 2cm;
        }
        th, td { 
            padding-top: 2px !important;
            padding-bottom: 2px !important;
        }
    </style>
</head>
<body style="font-size:10px;">
    <div class="container mt-4">
        <div class="row">
            <div style="text-align: center">
                <h4>KARDEX FISICO Y VALORADO</h4>
            </div>
            <div class="col-md-12">
                <b>CODIGO:</b> {{ $product->code }} &nbsp;&nbsp;&nbsp; <b>PRODUCTO:</b> {{ $product->name }}<br>
                <b>SALDO INICIAL:</b> &nbsp;&nbsp;&nbsp; <b>SALDO FINAL: {{ $subtotal }}</b>
                <table class="table" border="1" width="100%">
                    <caption>Lista de Movimientos</caption>
                    <thead>
                      <tr>
                        <th scope="col">DETALLE</th>
                        <th scope="col">{{ $product->name }}</th>
                        <th scope="col" colspan="3">CONTROL FISICO</th>
                        <th scope="col" colspan="3">CONTROL VALORADO</th>
                        <th scope="col" colspan="2">CODIGO</th>
                        <th scope="col" colspan="2">{{ $product->code }}</th>
                      </tr>
                      <tr>
                        <th scope="col" width="30%">FECHA</th>
                        <th scope="col">DESCRIPCION</th>
                        <th scope="col">ENTRADA</th>
                        <th scope="col">SALIDA</th>
                        <th scope="col">SALDO</th>
                        <th scope="col">Bs<br>US$</th>
                        <th scope="col">COSTO<br>UNITARIO</th>
                        <th scope="col">COSTO<br>TOTAL</th>
                        <th scope="col">DESTINO</th>
                        <th scope="col">GUIA No.</th>
                        <th scope="col">TAL. No.</th>
                        <th scope="col">NOMBRE</th>
                      </tr>
                    </thead>
                    <tbody>
                        @foreach ($existencias as $item)
                        <tr>
                            <td>{{ $item->created_at }}</td>
                            <td align="right">{{ $item->tipo }}</td>
                            <td align="right">
                                @if($item->tipo =='INGRESO')
                                    {{ $item->quantity }}
                                @endif
                            </td>
                            <td align="right">
                                @if($item->tipo == 'SALIDA')
                                    {{ $item->quantity }}
                                @endif
                            </td>
                            <td align="right">{{ $item->saldo}}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        @endforeach
                        <tr>
                            <td scope="row" colspan="4" align="right">SALDO FINAL</td>
                            <td align="right">{{ $subtotal }}</td>
                            <td colspan="7"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

prueba2023/resources/views/admin/product/show.blade.php
@extends('layouts/admin')

@section('title', 'Información Producto')

@section('style')
@endsection

@section('content')

	<div class="content-wrapper">
	  <div >
		    <nav aria-label="breadcrumb">
		  	<ol class="breadcrumb">
		  		<li class="breadcrumb-item"><a href="#">Panel| Administrador</a></li>
		  		<li class="breadcrumb-item"><a href="{{ route('providers.index') }}">Productos</a></li>
		  		<li class="breadcrumb-item active" aria-current="page">{{ $product->name }}</li>
		  	</ol>
		  </nav>
	  </div>
	  	  <div class="row">

	   <div class="col-md-12 grid-margin stretch-card">
	      <div class="card">
	        <div class="card-body">
						<div>
							<h4 class="card-header text-center mb-2" style="background-color: rgb(39, 47, 47); color:white">INFORMACIÓN DEL ARTÍCULO</h4>
						</div>
	        	<div class="row">

	        		<div class="col-lg-4">
	        			<div class="border-bottom text-center pb-4">

	        				@if (isset($product->image))
	        					<img src="{{ asset('image/'.$product->image) }}" alt="profile" class="img-lg rounded-circle mb-3">
	        				@endif

	        				<h3>{{ $product->name }}</h3>
	        				<div class="d-flex justify-content-between">
	        				</div>
	        			</div>

	        			<div class="border-bottom py-4">
	        				<div class="list-group">

	        					@if ($product->status == 'ACTIVE')
	        						<button class="btn btn-block btn-success">Activo</button>
	        					@else
	        						<button class="btn btn-block btn-danger">Desactivado</button>
	        					@endif
	        				</div>
	        			</div>

	        		</div>

	        		<div class="col-lg-8 pl-lg-5">
								
<!-- 'code', 'name', 'stock', 'image', 'sell_price', 'category_id', 'provider_id' -->
	        			<div class="profile-feed">
	        				<div class="d-flex align-items-start profile-feed-item">

	        					<div class="form-group col-md-6">

	        						<strong><i class="fab fa-product-hunt mr-1"></i>Código</strong>
	        						<p class="text-muted">{{ $product->code }}</p>
	        						<hr>

	        						<strong><i class="far fa-id-card mr-1"></i>Nombre</strong>
	        						<p class="text-muted">{{ $product->name }}</p>
	        						<hr>

	        						<strong><i class="fas fa-address-card mr-1"></i>Stock</strong>
	        						<p class="text-muted">{{ $product->stock }}</p>
	        						<hr>
											
											<strong><i class="fas fa-map-marked-alt mr-1"></i>Código de Barras</strong>
	        						<p class="text-muted">
												{!!DNS1D::getBarcodeHTML($product->code, 'EAN13'); !!}
											</p>
	        					</div>


	        					<div class="form-group col-md-6">
	        						<strong><i class="fas fa-mobile-alt mr-1"></i>Precio de Venta</strong>
	        						<p class="text-muted">{{ $product->price }} Bs.</p>
	        						<hr>

	        						<strong><i class="fas fa-map-marked-alt mr-1"></i>Proveedor</strong>
	        						<p class="text-muted">{{ $product->provider->name }}</p>
	        						<hr>

											<strong><i class="fas fa-envelope mr-1"></i>Categoria</strong>
	        						<p class="text-muted">{{ $product->category->name }}</p>
	        						<hr>
	        					</div>
										
	        				</div>
	        			</div>
	        		</div>

	        	</div>

	        </div>

	        <div class="card-footer text-muted">
	        	<a href="{{ route('products.index') }}" class="btn btn-info float-right">Regresar</a>
	        </div>

	      </div>
	    </div>

	  </div>
@endsection

@section('script')
@endsection