prueba2023/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PlatosController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProformasController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\TransferProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login2');
});

Route::get('/prueba', function () {
    return view('prueba');
});

Route::get('sales/reports_day', [ReportController::class, 'reports_day'])->name('reports.day');
Route::get('sales/reports_date', [ReportController::class, 'reports_date'])->name('reports.date');
Route::post('sales/reports_result', [ReportController::class, 'reports_result'])->name('reports.result');

Route::resource('users', UserController::class)->names('users');

Route::resource('categories', CategoryController::class)->names('categories');

Route::resource('platos', PlatosController::class)->names('platos');

Route::resource('warehouses', WarehouseController::class)->names('warehouses');

Route::resource('transfers', TransferProductController::class)->names('transfers');

Route::resource('marcas', \App\Http\Controllers\MarcaController::class);

Route::resource('medidas', \App\Http\Controllers\MedidaController::class);

Route::resource('clients', ClientController::class)->names('clients');

Route::resource('providers', ProviderController::class)->names('providers');

Route::resource('products', ProductController::class)->names('products');
Route::get('products/pdf/{product}', [ProductController::class, 'pdf'])->name('products.pdf');
Route::get('change_status/products/{product}', [ProductController::class, 'change_status'])->name('products.change.status');

Route::resource('purchases', PurchaseController::class)->names('purchases');
Route::post('change_status/purchases/{purchase}', [PurchaseController::class, 'change_status'])->name('purchases.change.status');
Route::get('purchases/pdf/{purchase}', [PurchaseController::class, 'pdf'])->name('purchases.pdf');

Route::resource('proformas', ProformasController::class)->names('proformas');
Route::get('proformas/pdf/{proforma}', [ProformasController::class, 'pdf'])->name('proformas.pdf');

Route::resource('sales', SaleController::class)->names('sales');
Route::get('sales/pdf/{sale}', [SaleController::class, 'pdf'])->name('sales.pdf');
Route::post('change_status/sales/{sale}', [SaleController::class, 'change_status'])->name('sales.change.status');

Route::resource('roles', RoleController::class)->names('roles');
Route::resource('permissions', PermissionController::class)->names('permissions');

Route::get('get_products_by_barcode', [ProductController::class, 'get_products_by_barcode'])->name('get_products_by_barcode');
Route::get('get_products_by_id', [App\Http\Controllers\ProductController::class, 'get_products_by_id'])->name('get_products_by_id');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

prueba2023/app/Models/TransferProduct.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TransferProduct extends Model
{
    use HasFactory;

    protected $table = "transfer_products";

    public function warehouse_from(){
        return $this->belongsTo('App\Models\Warehouse', 'warehouse_from_id', 'id');
    }

    public function product(){
        return $this->belongsTo('App\Models\Product', 'product_id', 'id');
    }

    public function warehouse_to(){
        return $this->belongsTo('App\Models\Warehouse', 'warehouse_to_id', 'id');
    }
}

prueba2023/app/Http/Controllers/TransferProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\TransferProduct;
use App\Models\Warehouse;
use DB;

class TransferProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transfers = TransferProduct::all();
        return view('admin.transfer_products.index', compact('transfers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $warehouses = Warehouse::all();
        return view('admin.transfer_products.create', compact('warehouses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tp = new TransferProduct();
        $tp->warehouse_from_id = $request->warehouse_from_id;
        $tp->product_id = $request->product_id;
        $tp->quantity = $request->quantity;
        $tp->warehouse_to_id = $request->warehouse_to_id;
        $tp->save();

        $this->add_or_sum_product_in_warehouse($request->product_id, $request->warehouse_to_id, $request->quantity);
        $this->remove_quantity($request->product_id, $request->warehouse_from_id, $request->quantity);

        return redirect()->route('transfers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tp = TransferProduct::findOrFail($id);
        return view('admin.transfer_products.report', compact('tp'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function add_or_sum_product_in_warehouse($product_id, $warehouse_id, $quantity){
        $current_quantity = 0;
        $new_quantity = 0;
        $in_warehouse = DB::table("product_warehouses")
        ->where('product_id', $product_id)
        ->where('warehouse_id',$warehouse_id)
        ->get();

        if($in_warehouse->count() > 0){
            $current_quantity = $in_warehouse[0]->quantity;
            $new_quantity = $current_quantity + $quantity;
            DB::table('product_warehouses')
                ->where('product_id', $product_id)
                ->where('warehouse_id',$warehouse_id)
                ->update(['quantity'=>$new_quantity]);
        }else{
            DB::table('product_warehouses')
                ->insert(['product_id'=>$product_id, 'warehouse_id'=>$warehouse_id, 'quantity'=>$quantity]);
        }
    }

    public function remove_quantity($product_id, $warehouse_id, $quantity){
        $current_quantity = 0;
        $new_quantity = 0;
        $in_warehouse = DB::table("product_warehouses")
        ->where('product_id', $product_id)
        ->where('warehouse_id',$warehouse_id)
        ->get();

        if($in_warehouse->count() > 0){
            $current_quantity = $in_warehouse[0]->quantity;
            $new_quantity = $current_quantity - $quantity;
            DB::table('product_warehouses')
                ->where('product_id', $product_id)
                ->where('warehouse_id',$warehouse_id)
                ->update(['quantity'=>$new_quantity]);
        }
    }
}

prueba2023/resources/views/admin/transfer_products/_form.blade.php
  <input type="hidden" name="current_quantity" id="current_quantity">
  <div class="form-group col-12">
    <label for="warehouse_from_id">Almacen Origen : </label>
    <select name="warehouse_from_id" id="warehouse_from_id" class="form-control">
      <option value="">Seleccione</option>
      @foreach($warehouses as $warehouse)
        <option value="{{ $warehouse->id }}" data-products='{{$warehouse->products}}'>{{ $warehouse->name }}</option>
      @endforeach
    </select>
  </div>
  <div class="form-group col-12">
    <label for="product_id">Producto : </label>
    <select name="product_id" id="product_id" class="form-control">
      <option value="">Seleccione</option>
    </select>
  </div>
  <div class="form-group col-12">
    <label for="quantity">Cantidad : </label>
    <input type="text" name="quantity" id="quantity" class="form-control" />
  </div>
  <div class="form-group col-12">
    <label for="warehouse_to_id">Almacen Destino : </label>
    <select name="warehouse_to_id" id="warehouse_to_id" class="form-control">
      <option value="">Seleccione</option>
       @foreach($warehouses as $warehouse)
        <option value="{{ $warehouse->id }}" data-products='{{$warehouse->products}}'>{{ $warehouse->name }}</option>
      @endforeach
    </select>
  </div>

prueba2023/resources/views/admin/transfer_products/create.blade.php
@extends('layouts.admin')

@section('title', 'Registrar Transferencia')
    
@section('options')
    {{-- <li class="nav-item nav-settings d-none d-lg-block">
        <a href="#" class="nav-link">
            <i class="fa fa-elipsis-h"></i>
        </a>
    </li> --}}
@endsection

@section('content')
    <div class="content-wrapper">
        <div >
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('transfers.index') }}">Transferencias</a></li>
                    <li class="breadcrumb-item active">Registrar Transferencia</li>
                </ol>
            </nav>
        </div>
        <div class="container ">
            <div class="abs-center">
                <div class="card card-primary">
                    <div class="card-header" style="background-color:rgb(57, 62, 66); color:white">
                        <h1 style="text-align:center">REGISTRAR NUEVA TRANSFERENCIA DE INVENTARIO</h1>
                    </div>
                    <div class="card-body">

                        {!! Form::open(['route' => 'transfers.store', 'method' => 'POST', 'id'=>'send_create']) !!}

                            @include('admin.transfer_products._form')

                            <div class="card-footer text-center">
                                <button type="submit" class="btn btn-success mr-2">+ Registrar</button>
                                <a href="{{ route('transfers.index') }}" class="btn btn-info">Cancelar</a>
                            </div>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            $("#warehouse_from_id").change(function(){
                let data = JSON.parse($("#warehouse_from_id option:selected").attr("data-products"));
                console.log(data);
                $("#product_id").empty();
                $("#product_id").append("<option value=''>Selecciona</option>");
                $.each(data, function(v,e){
                    $("#product_id").append("<option data-quantity='"+e.pivot.quantity+"' value='"+e.id+"'>"+e.name+" ("+e.pivot.quantity+")</option>");
                });
            });

            $("body").on('change','#product_id', function(){
                let quantity = $("#product_id option:selected").attr("data-quantity");
                $("#current_quantity").val(quantity);
            });

            $("#send_create").submit(function(){
                let quantity_selected = parseInt($("#current_quantity").val());
                let quantity = parseInt($("#quantity").val());
                if(quantity > quantity_selected){
                    alert("No puedes transferir un monto mayor a la existencia");
                    return false;
                }else{
                    return true;
                }
            });
        });
    </script
@endsection

prueba2023/resources/views/admin/transfer_products/index.blade.php
@extends('layouts.admin')

@section('title', 'Gestión de Transferencias de Productos')
    
@section('create')

@endsection

@section('styles')
    <style type="text/css">
        .unstyled-button {
            border: none;
            padding: 0;
            background: none
        }
    </style>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.3.0/css/responsive.dataTables.min.css">
@endsection

@section('content')
    <div class="content-wrapper">
        <div>
            <h3 class="text-center">
                Gestión de Transferencias de Productos
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item active">Transferencias de Productos</li>
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <div class="d-flex justify-content-between mb-4">
                            <h4 class="">Lista de Transferencias de Productos</h4>
                            <div>                  
                                <div>
                                    <a href="{{ route('transfers.create') }}"  class="btn btn-success">+ Nueva Transferencia</a>
                                </div>
                            </div>
                        </div>

                        <div>
                            <table id="detalle" class="table">
                                <thead class="bg-dark text-white">
                                    <tr>
                                        <th>Id</th>
                                        <th>Almacen Origen</th>
                                        <th>Producto</th>
                                        <th>Cantidad</th>
                                        <th>Almacen Destino</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($transfers as $transfer)
                                        <tr>
                                            <th scope="row">{{ $transfer->id }}</th>
                                            <td>{{ $transfer->warehouse_from->name }}</td>
                                            <td>{{ $transfer->product->name }}</td>
                                            <td>{{ $transfer->quantity }}</td>
                                            <td>{{ $transfer->warehouse_to->name }}</td>
                                            <td>
                                                <a href="{{ route('transfers.show',$transfer->id) }}" class="btn btn-success">Ver Reporte</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {

            $('#detalle').DataTable({

                "order": [
                    [0, 'desc']
                ],
                "lengthMenu": [
                    [5, 10, 50, -1],
                    [5, 10, 50, "Todo"]
                ],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Ningun registro encontrado",
                    "info": "Mostrando la página _PAGE_ de _PAGES_",
                    "infoEmpty": "",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    'search': 'Buscar:',
                    'paginate': {
                        'next': 'Siguiente',
                        'previous': 'Anterior'
                    }

                },
            });

        });
    </script>
@endsection

prueba2023/resources/views/admin/transfer_products/report.blade.php
@extends('layouts.admin')

@section('title', 'Reporte Transferencia')
    
@section('create')

@endsection

@section('styles')
    <style type="text/css">
        .unstyled-button {
            border: none;
            padding: 0;
            background: none
        }
    </style>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.3.0/css/responsive.dataTables.min.css">
@endsection

@section('content')
    <div class="content-wrapper">
        <div>
            <h3 class="text-center">
                Reporte de Transferencia
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Panel Administrador</a></li>
                    <li class="breadcrumb-item active">Reporte de Transferencia</li>
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div>
                            <table class="table" id="detalle">
                              <thead class="thead-dark">
                                <tr>
                                  <th scope="col">Almacen Origen</th>
                                  <th scope="col">Producto</th>
                                  <th scope="col">Cantidad</th>
                                  <th scope="col">Almacen Destino</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>{{ $tp->warehouse_from->name }}</td>
                                  <td>{{ $tp->product->name }}</td>
                                  <td>{{ $tp->quantity }}</td>
                                  <td>{{ $tp->warehouse_to->name }}</td>
                                </tr>
                              </tbody>
                            </table>
                            <button class="btn btn-success" id="export" type="button">Imprimir</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.5/jspdf.plugin.autotable.min.js"></script>
    <script src="https://www.jqueryscript.net/demo/export-table-json-csv-txt-pdf/src/tableHTMLExport.js"></script>
    <script>
        $(document).ready(function(){
            $("#export").click(function(){
                $("#detalle").tableHTMLExport({

                  // csv, txt, json, pdf
                  type:'pdf',

                  // file name
                  filename:'export.pdf'
                  
                });
            });
        });
    </script>
@endsection